### ISSUE TITLE
切换为七牛云无法正常使用

### ISSUE THREAD

**Issue by amw0918** [dairidong/dcat-media-manager#3]
已生成安装了插件并启动
本地上传和管理可以正常使用
当切换到七牛下页面出现报错
文档中关于七牛云相关的配置步骤不是很清晰
能否补充下七牛云相关的配置

**Comment by dairidong** [comment]
@amw0918 
请附上报错日志，如果是配置相关的报错，其实报错信息已经给出，使用七牛云驱动需要在 `filesystem.php` 的七牛云配置上添加参数 `s3_region` 和 `s3_endpoint`，例如：
```php
'qiniu' => [
    'driver' => 'qiniu',
    'access_key' => env('QINIU_ACCESS_KEY'),
    'secret_key' => env('QINIU_SECRET_KEY'),
    'bucket' => env('QINIU_BUCKET'),
    'domain' => env('QINIU_DOMAIN'), // or host: https://xxxx.clouddn.com

     's3_region' => 'cn-south-1',
     's3_endpoint' => 'https://s3-cn-south-1.qiniucs.com',
],
```
具体需要填写配置查看七牛云对象存储的 S3 兼容文档，这个是根据 bucket 所在区域相关的。

**Comment by amw0918** [comment]
感谢回复！
当我设置好七牛配置后，出现一下错误：
**Driver [qiniu] is not supported.**
配置信息如下：
```
'qiniu' => [
            'driver'     => 'qiniu',
            'access_key' => env('QINIU_ACCESS_KEY', ''),
            'secret_key' => env('QINIU_SECRET_KEY', ''),
            'bucket'     => env('QINIU_BUCKET', ''),
            'domain'     => env('QINIU_DOMAIN', ''),
            's3_region' => 'cn-south-1',
            's3_endpoint' => 'https://s3-cn-south-1.qiniucs.com',
        ],
```

**Comment by dairidong** [comment]
@amw0918 
这是来自 Laravel 的报错而无关本扩展，检查你的依赖安装，本扩展内的七牛云支持需要 composer 安装 `overtrue/laravel-filesystem-qiniu`

**Comment by amw0918** [comment]
@dairidong 抱歉，现在已经安装好了，但是又出现了以下错误：
我这个是一个权限的laravel项目， 
url：http://121.41.27.190:5197/admin/media?disk=qiniu
登录帐号密码都是默认的admin
