### ISSUE TITLE
请问下七牛云上传后，页面如何启动分页

### ISSUE THREAD

**Issue by amw0918** [dairidong/dcat-media-manager#4]
当我上传到七牛云图片量大以后，导致页面卡死

**Comment by dairidong** [comment]
@amw0918 
只能建议你的应用根据一定规则对图片目录分类，因为我依赖的 sdk 也没有实现分页功能 [overtrue/laravel-filesystem-qiniu](https://github.com/overtrue/laravel-filesystem-qiniu)

**Comment by amw0918** [comment]
非常感谢您的回复，谢谢。我自己再研究一下

**Comment by dairidong** [comment]
@amw0918 
不清楚你目前的卡死原因在后端还是前端，如果单纯是前端图片加载的问题，一个简单的方案是：

采用本地安装的方式，然后编辑一下这个文件里的 `<img>` 标签：https://github.com/dairidong/dcat-media-manager/blob/main/src/Files/Image.php#L10
在标签属性里加上 `loading="lazy"` https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/img#loading
